# Generated by Django 5.0.1 on 2024-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
